### ISSUE TITLE
copyright credit

### ISSUE THREAD

**Issue by stef-k** [mertyildiran/Dermatron#1]
Hi there, I've notice that you are using the majority of the code from https://github.com/stef-k/meteor_project_layout for the alien script https://github.com/mertyildiran/Dermatron/blob/master/alien but you have removed the copyright notice from it.

Could you please put back the copyright - credit to author?

**Comment by mertyildiran** [comment]
@stef-k Your development was inactive since Dec 18. 2014 so I have inherited your script. You can put your name back with a pull request. Any contributions are also welcomed. Thanks a lot!

**Comment by mertyildiran** [comment]
Fixed with: b707c3dee9763edc8ac20296198f77a1a061884e
